export class Url{
    public static urlItems: any = "http://localhost:3000/items"
    public static urlConstantes: any = "http://localhost:3000/Constantes"
    public static urlToDo: any = ""
    public static getPersonajesVistaPrevia = "http://localhost:8089/get-personajes-foto"
    public static getClasesPjs = "http://localhost:8089/get-clases"
    public static postNuevoPj = "http://localhost:8089/nuevo-personaje"
    public static getInfoPersonaje = "http://localhost:8089/personaje-completo/?id="
    public static getPendiente = "http://localhost:8089/tareas/get-tareas"
    public static PostPendiente = "http://localhost:8089/tareas/crear"
    public static deletePendiente = "http://localhost:8089/tareas/delete?id="
    public static getLinks = "http://localhost:8089/link-utiles/get-links?categoria="
    public static editLinks = "http://localhost:8089/link-utiles/modificar-link"
    public static addLinks = "http://localhost:8089/link-utiles/add-link"
    public static deleteLinks = "http://localhost:8089/link-utiles/delete-link?linkId="
}